#!/bin/bash
# Script to create GitHub issue and PR for becquerel feature

echo "=========================================="
echo "Becquerel Feature Submission Instructions"
echo "=========================================="
echo ""
echo "Since we don't have write access to the upstream repo,"
echo "here are the steps to submit this feature:"
echo ""
echo "1. FORK THE REPOSITORY"
echo "   Go to: https://github.com/lbl-anp/becquerel"
echo "   Click 'Fork' button"
echo ""
echo "2. ADD YOUR FORK AS REMOTE"
echo "   cd /tmp/becquerel"
echo "   git remote add myfork https://github.com/YOUR_USERNAME/becquerel.git"
echo ""
echo "3. PUSH THE FEATURE BRANCH"
echo "   git push myfork feature/expose-migrad-kwargs"
echo ""
echo "4. CREATE PULL REQUEST"
echo "   Go to: https://github.com/lbl-anp/becquerel/compare"
echo "   - Base: main"
echo "   - Compare: YOUR_USERNAME:feature/expose-migrad-kwargs"
echo "   - Title: feat: expose migrad kwargs in Fitter.fit() method"
echo "   - Description: Copy from PR_DESCRIPTION.md"
echo ""
echo "5. (OPTIONAL) CREATE FEATURE REQUEST ISSUE FIRST"
echo "   Go to: https://github.com/lbl-anp/becquerel/issues/new"
echo "   - Title: Feature Request: Expose Minuit migrad() kwargs in Fitter.fit()"
echo "   - Description: Copy from FEATURE_REQUEST.md"
echo ""
echo "=========================================="
echo "Files prepared in /tmp/becquerel:"
echo "=========================================="
ls -1 /tmp/becquerel/*.md /tmp/becquerel/*.py 2>/dev/null | grep -E "(FEATURE|PR_|test_migrad|SUBMISSION)" || true
echo ""
echo "Commits on branch:"
git log --oneline feature/expose-migrad-kwargs ^main
