name: coveralls

on:
  push:
    branches: [$default-branch]
  pull_request:
  workflow_dispatch:

jobs:
  coveralls_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --only-binary=numpy,scipy -r requirements-dev.txt
      - name: Install package
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test

  coveralls_finish:
    needs: coveralls_test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
          debug: true
