name: coveralls

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  coveralls_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --only-binary=numpy,scipy -r requirements-dev.txt
    - name: Install package
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        parallel: true
        flag-name: Unit Test

  coveralls_finish:
    needs: coveralls_test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        parallel-finished: true
        debug: true
